fitness_management/user/models.py
from ..database import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(80), unique=False)
    last_name = db.Column(db.String(80), unique=False)
    role = db.Column(db.String(80), unique=False)
    email = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(80), unique=False)

fitness_management/user/routes.py
import ast
from flask import render_template, session, request, redirect, url_for, Blueprint, flash, make_response
from ..database import db
from .models import User
import json
from werkzeug.security import generate_password_hash, check_password_hash
from flask_mail import Mail, Message
import random
import hashlib

user_bp = Blueprint("user_bp", __name__)
mail = Mail()
otp = ''.join(random.choices('123456789', k=6))


def login_required(func):
    def wrapper(*args, **kwargs):
        if 'email' in session:
            return func(*args, **kwargs)
        else:
            flash(f'Please login first', 'danger')
            return redirect(url_for('user_bp.user_login'))
    wrapper.__name__ = func.__name__
    return wrapper


@user_bp.route("/")
def home_page():
    return render_template('user/home_page.html')


@user_bp.route("/user/register", methods=['GET', 'POST'])
def user_register():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        if User.query.filter_by(email=email).first():
            flash(f'{email} is already taken!!! choose other usernmae', 'warning')
        elif password != confirm_password:
            flash("Password shuld be match!!!!!", "warning")
        else:
            user = User(
                first_name=request.form.get("fname"),
                last_name=request.form.get("lname"),
                role=request.form.get("role"),
                email=email,
                password=hashlib.sha256(password.encode()).hexdigest()
            )
            db.session.add(user)
            db.session.commit()
            flash(
                f'Welcome {request.form.get("fname")} , Thank you for Regiustering', "success")
            return redirect(url_for('user_bp.user_login'))
    return render_template("user/register.html")


@user_bp.route("/user/login", methods=['GET', 'POST'])
def user_login():
    if 'email' in session:
        current_user = get_current_user()
        if current_user.role == "Admin":
            return redirect(url_for('user_bp.admin_dashboard'))
        elif current_user.role == 'Trainer':
            return redirect(url_for('user_bp.trainer_dashboard'))
        else:
            return redirect(url_for('user_bp.member_dashboard'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = hashlib.sha256(request.form.get(
            'password').encode()).hexdigest()
        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                session['email'] = email
                if user.role == 'Admin':
                    return redirect(url_for('user_bp.admin_dashboard'))
                elif user.role == 'Trainer':
                    return redirect(url_for('user_bp.trainer_dashboard'))
                else:
                    return redirect(url_for('user_bp.member_dashboard'))
            else:
                flash("Password is not correct!!!!", "danger")
                return redirect(url_for('user_bp.user_login'))
        else:
            flash("Email is not correct!!!!", "danger")
            return redirect(url_for('user_bp.user_login'))
    return render_template('user/login.html')


@user_bp.route('/profile')
@login_required
def user_profile():
    current_user = get_current_user()
    return render_template('user/user_profile.html', current_user=current_user)


@user_bp.route('/user_update', methods=['GET', 'POST'])
@login_required
def user_update():
    current_user = get_current_user()
    print(current_user.first_name)
    print(session.get("email"))
    if request.method == 'POST':
        first_name = request.form.get("fname")
        last_name = request.form.get("lname")
        role = request.form.get("role")
        email = request.form.get("email")
        current_user.first_name = first_name
        current_user.last_name = last_name
        current_user.role = role
        current_user.email = email
        db.session.commit()
        flash("Your Profile has been updated", "success")
        return redirect(url_for('user_bp.user_profile'))
    return render_template('user/user_update.html', current_user=current_user)


def get_current_user():
    return User.query.filter_by(email=session.get("email")).first()


@user_bp.route('/admin_dashboard')
@login_required
def admin_dashboard():
    current_user = get_current_user()
    if current_user.role != 'Admin':
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/admin_dashboard.html', current_user=current_user)


@user_bp.route('/trainer_dashboard')
@login_required
def trainer_dashboard():
    current_user = get_current_user()
    if current_user.role != 'Trainer':
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/trainer_dashboard.html', current_user=current_user)


@user_bp.route('/member_dashboard')
@login_required
def member_dashboard():
    current_user = get_current_user()
    if current_user.role not in ['Admin', 'Trainer', 'Member']:
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/member_dashboard.html', current_user=current_user)


@user_bp.route('/all_members')
@login_required
def all_members():
    current_user = get_current_user()
    if current_user.role != "Admin":
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    all_members = User.query.filter_by(role='Member').all()
    return render_template('user/all_members.html', all_members=all_members)


@user_bp.route('/all_trainers')
@login_required
def all_trainers():
    current_user = get_current_user()
    if current_user.role != "Admin":
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    all_trainers = User.query.filter_by(role='Trainer').all()
    print("total is :", len(all_trainers))
    return render_template('user/all_trainers.html', all_trainers=all_trainers)


@user_bp.route("/create_new_password", methods=['GET', 'POST'])
def create_new_password():
    if request.method == 'POST':
        email = request.form.get("email")
        user_exists = db.session.query(User).filter(
            User.email == email).first()
        if not user_exists:
            flash('Email does not exist !', 'danger')
        else:
            session['email'] = email
            return redirect(url_for('user_bp.update_password', email=email))
    return render_template("user/create_new_password.html")


@user_bp.route("/update_password", methods=['GET', 'POST'])
def update_password():
    if request.method == 'POST':
        user = db.session.query(User).filter(
            User.email == session.get("email")).first()
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        if password != confirm_password:
            flash('Password does not match !', 'danger')
        else:
            user.password = hashlib.sha256(password.encode()).hexdigest()
            session.clear()
            db.session.commit()
            return redirect(url_for('user_bp.user_login'))
    return render_template('user/update_password.html')


@login_required
@user_bp.route('/user/logout')
def user_logout():
    session.pop("email")
    return redirect(url_for('user_bp.home_page'))

fitness_management/templates/user/admin_dashboard.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <h2>Welcome to Admin Dashboard</h2>
    <!-- Add your member-specific features here -->
    <div class="row mt-5">
        <div class="col-md-6"><a href="{{url_for('user_bp.all_members')}}" class="btn btn-info btn-custom">See All Members</a></div>
        <div class="col-md-6"><a href="{{url_for('user_bp.all_trainers')}}" class="btn btn-info btn-custom"> See All Trainers</a></div>
    </div>
</div>
{% endblock%}

fitness_management/templates/user/all_members.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <h1>All members page</h1>
    {% if all_members %}
    <table class="modern-table">
        <thead>
          <tr>
            <th>Sr</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for member in all_members %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{ member.first_name }}</td>
            <td>{{ member.last_name }}</td>
            <td>{{ member.email }}</td>
            <td><a href="#"
                class="btn btn-info btn-sm">Edit</a></td>
            <td>
                <a href="#"
                class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="text-center">
        <span class="emoji">&#x1F614;</span>
        <p class="text-danger h3">No Member is Found</p>
      </div>
    {% endif %}
    <div class="text-center mt-4">
        <a href="{{ url_for('user_bp.admin_dashboard') }}" class="btn btn-info btn-custom">Back to Dashboard</a>
    </div>
    
</div>
{% endblock %}

fitness_management/templates/user/all_trainers.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <h1>All Trainers page</h1>
    {% if all_trainers %}
    <table class="modern-table">
        <thead>
          <tr>
            <th>Sr</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for trainer in all_trainers %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{ trainer.first_name }}</td>
            <td>{{ trainer.last_name }}</td>
            <td>{{ trainer.email }}</td>
            <td><a href="#"
                class="btn btn-info btn-sm">Edit</a></td>
            <td>
                <a href="#"
                class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="text-center">
        <span class="emoji">&#x1F614;</span>
        <p class="text-danger h3">No Trainer is Found</p>
      </div>
    {% endif %}
    <div class="text-center mt-4">
        <a href="{{ url_for('user_bp.admin_dashboard') }}" class="btn btn-info btn-custom">Back to Dashboard</a>
    </div>
    

</div>
{% endblock %}

fitness_management/templates/user/create_new_password.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 mt-4">
            <div class="card">
                <h2 class="text-center">Forgot Password</h2>
                <form method="post">
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter Email">
                    </div>
                    <div class="row mt-4">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info btn-custom btn-block">Submit</button>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-warning btn-custom btn-block" href="{{url_for('user_bp.user_login')}}" >Cancel</a>
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
{% endblock %}

fitness_management/templates/user/home_page.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-md-5 bg-info">
            <h1>Write something</h1>
        </div>
        <div class="col-md-7">
            <img src="{{ url_for('static', filename='images/main_image.jpg') }}" width="640px%" height="800px" alt="No Image">
        </div>
    </div>
    

</div>
{% endblock %}

fitness_management/templates/user/login.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 mt-5">
                {% include '_messages.html' %}
                <div class="card">
                    <h2 class="text-center">User Login</h2>
                    <form method="post">
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" name="email" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Enter Password">
                        </div>
                        <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Login</button>
                    </form>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <span class="mt-3">New User? &nbsp; <a href="{{url_for('user_bp.user_register')}}">Create An Account</a></span>
                        </div>
                        <div class="col-md-6">
                            <span class="mt-3">Forgot Password? &nbsp; <a href="{{url_for('user_bp.create_new_password')}}">Create New</a></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock content %}

fitness_management/templates/user/member_dashboard.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <!-- Add your member-specific features here -->
    <div class="row mt-4">
        <div class="col-md-6"><h2>Welcome to Member Dashboard</h2></div>
        <div class="col-md-6 text-center">
            <a href="{{url_for('workout_bp.list_workouts')}}" class="btn btn-info btn-custom">All Workout</a>
        </div>
    </div>
</div>
{% endblock%}

fitness_management/templates/user/register.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
{% include '_messages.html' %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 mt-5">
            <div class="card">
                <h2 class="text-center">Sign-Up Form</h2>
                <form method="post" class="font-weight-bold">
                    <div class="form-group">
                        <label for="fname">First Name</label>
                        <input type="text" class="form-control" name="fname" placeholder="Enter First Name">
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name</label>
                        <input type="text" class="form-control" name="lname" placeholder="Enter Last Name">
                    </div>
                    <div class="form-group">
                        <label for="firstName">Role</label>
                        <select name="role" id="role" class="form-control" required>
                            <option value="">Select a brand</option>
                            <option value="Member">Member</option>
                            <option value="Trainer">Trainer</option>
                            <option value="Admin">Admin</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter Email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Enter Password">
                    </div>
                    <div class="form-group">
                        <label for="password">Confirm Password</label>
                        <input type="password" class="form-control" name="confirm_password" placeholder="Enter Password">
                    </div>
                    <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Sign Up</button>
                </form>
                <span class="mt-3">Allready have an Account? &nbsp; <a href="{{url_for('user_bp.user_login')}}">Login</a></span>
            </div>
        </div>
        <div class="col-md-3"></div>

    </div>
</div>
{% endblock content %}

fitness_management/templates/user/trainer_dashboard.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">


    <div class="row">
        <div class="col-md-6">
                <!-- Add your trainer-specific features here -->
            <h2>Welcome to Trainer Dashboard</h2>
        </div>
        <div class="col-md-6        ">
            <img src="{{ url_for('static', filename='images/gym_trainer.jpg') }}" width="550px%" height="800px" alt="No Image">
        </div>
    </div>
</div>
{% endblock%}

fitness_management/templates/user/update_password.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 mt-4">
            <div class="card">
                <h2 class="text-center">Update Password</h2>
                <form method="post">
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Enter Password">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="confirm_password" placeholder="Enter Password">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info btn-custom btn-block">Change Password</button>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-warning btn-custom btn-block" href="{{url_for('user_bp.user_login')}}">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
{% endblock %}

fitness_management/templates/user/user_profile.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container mt-5">
<div class="row">
    <div class="col-md-12">
        {% include '_messages.html' %}
        <div class="card">
            <h1>This is user profile page</h1>
            <h5>First Name : {{current_user['first_name']}}</h5>
            <h5>Last Name : {{current_user['last_name']}}</h5>
            <h5>Email : {{current_user['email']}}</h5>
            <div class="row">
                <div class="col-md-6">
                    <a href="{{ url_for('user_bp.user_update') }}" class="btn btn-info btn-custom btn-block">Update User</a>            
                </div>
                <div class="col-md-6">
                    {% if current_user.role == "Admin" %}
                    <a href="{{ url_for('user_bp.admin_dashboard') }}" class="btn btn-warning btn-custom btn-block">Cancel</a>
                    {% elif current_user.role == "Trainer" %}
                    <a href="{{ url_for('user_bp.trainer_dashboard') }}" class="btn btn-warning btn-custom btn-block">Cancel</a>
                    {% else %}
                    <a href="{{ url_for('user_bp.member_dashboard') }}" class="btn btn-warning btn-custom btn-block">Cancel</a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}

fitness_management/templates/user/user_update.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 mt-5">
            <div class="card">
                <h2 class="text-center">User Update Form</h2>
                <form method="post" class="font-weight-bold">
                    <div class="form-group">
                        <label for="fname">First Name</label>
                        <input type="text" value="{{current_user.first_name}}" class="form-control" name="fname" placeholder="Enter First Name">
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name</label>
                        <input type="text" value="{{current_user.last_name}}" class="form-control" name="lname" placeholder="Enter Last Name">
                    </div>
                    <div class="form-group">
                        <label for="firstName">Role</label>
                        <select name="role" id="role" class="form-control" required>
                            <option value="{{current_user.role}}">{{current_user.role}}</option>
                            <option value="Member">Member</option>
                            <option value="Trainer">Trainer</option>
                            <option value="Admin">Admin</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" value="{{current_user.email}}" class="form-control" name="email" placeholder="Enter Email">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Update User</button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{url_for('user_bp.user_profile')}}" class="btn btn-warning btn-custom btn-block mt-4">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <div class="col-md-3"></div>

    </div>
</div>
{% endblock content %}