fitness_management/user/routes.py
import ast
from flask import render_template, session, request, redirect, url_for, Blueprint, flash, make_response
from ..database import db
from .models import User
import json
from werkzeug.security import generate_password_hash, check_password_hash
from flask_mail import Mail, Message
import random
import hashlib

user_bp = Blueprint("user_bp", __name__)
mail = Mail()
otp = ''.join(random.choices('123456789', k=6))


def login_required(func):
    def wrapper(*args, **kwargs):
        if 'email' in session:
            return func(*args, **kwargs)
        else:
            flash(f'Please login first', 'danger')
            return redirect(url_for('user_bp.user_login'))
    wrapper.__name__ = func.__name__
    return wrapper


@user_bp.route("/")
def home_page():
    return render_template('user/home_page.html')


@user_bp.route("/user/register", methods=['GET', 'POST'])
def user_register():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        if User.query.filter_by(email=email).first():
            flash(f'{email} is already taken!!! choose other usernmae', 'warning')
        elif password != confirm_password:
            flash("Password shuld be match!!!!!", "warning")
        else:
            user = User(
                first_name=request.form.get("fname"),
                last_name=request.form.get("lname"),
                role=request.form.get("role"),
                email=email,
                password=hashlib.sha256(password.encode()).hexdigest()
            )
            db.session.add(user)
            db.session.commit()
            flash(
                f'Welcome {request.form.get("fname")} , Thank you for Regiustering', "success")
            return redirect(url_for('user_bp.user_login'))
    return render_template("user/register.html")


@user_bp.route("/user/login", methods=['GET', 'POST'])
def user_login():
    if 'email' in session:
        current_user = get_current_user()
        if current_user.role == "Admin":
            return redirect(url_for('user_bp.admin_dashboard'))
        elif current_user.role == 'Trainer':
            return redirect(url_for('user_bp.trainer_dashboard'))
        else:
            return redirect(url_for('user_bp.member_dashboard'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = hashlib.sha256(request.form.get(
            'password').encode()).hexdigest()
        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                session['email'] = email
                if user.role == 'Admin':
                    return redirect(url_for('user_bp.admin_dashboard'))
                elif user.role == 'Trainer':
                    return redirect(url_for('user_bp.trainer_dashboard'))
                else:
                    return redirect(url_for('user_bp.member_dashboard'))
            else:
                flash("Password is not correct!!!!", "danger")
                return redirect(url_for('user_bp.user_login'))
        else:
            flash("Email is not correct!!!!", "danger")
            return redirect(url_for('user_bp.user_login'))
    return render_template('user/login.html')


@user_bp.route('/profile')
@login_required
def user_profile():
    current_user = get_current_user()
    return render_template('user/user_profile.html', current_user=current_user)


@user_bp.route('/user_update', methods=['GET', 'POST'])
@login_required
def user_update():
    current_user = get_current_user()
    print(current_user.first_name)
    print(session.get("email"))
    if request.method == 'POST':
        first_name = request.form.get("fname")
        last_name = request.form.get("lname")
        role = request.form.get("role")
        email = request.form.get("email")
        current_user.first_name = first_name
        current_user.last_name = last_name
        current_user.role = role
        current_user.email = email
        db.session.commit()
        flash("Your Profile has been updated", "success")
        return redirect(url_for('user_bp.user_profile'))
    return render_template('user/user_update.html', current_user=current_user)


def get_current_user():
    return User.query.filter_by(email=session.get("email")).first()


@user_bp.route('/admin_dashboard')
@login_required
def admin_dashboard():
    current_user = get_current_user()
    if current_user.role != 'Admin':
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/admin_dashboard.html', current_user=current_user)


@user_bp.route('/trainer_dashboard')
@login_required
def trainer_dashboard():
    current_user = get_current_user()
    if current_user.role != 'Trainer':
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/trainer_dashboard.html', current_user=current_user)


@user_bp.route('/member_dashboard')
@login_required
def member_dashboard():
    current_user = get_current_user()
    if current_user.role not in ['Admin', 'Trainer', 'Member']:
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    return render_template('user/member_dashboard.html', current_user=current_user)


@user_bp.route('/all_members')
@login_required
def all_members():
    current_user = get_current_user()
    if current_user.role != "Admin":
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    all_members = User.query.filter_by(role='Member').all()
    return render_template('user/all_members.html', all_members=all_members)


@user_bp.route('/all_trainers')
@login_required
def all_trainers():
    current_user = get_current_user()
    if current_user.role != "Admin":
        flash('Unauthorized access', 'danger')
        return redirect(url_for('login'))
    all_trainers = User.query.filter_by(role='Trainer').all()
    print("total is :", len(all_trainers))
    return render_template('user/all_trainers.html', all_trainers=all_trainers)


@user_bp.route("/create_new_password", methods=['GET', 'POST'])
def create_new_password():
    if request.method == 'POST':
        email = request.form.get("email")
        user_exists = db.session.query(User).filter(
            User.email == email).first()
        if not user_exists:
            flash('Email does not exist !', 'danger')
        else:
            session['email'] = email
            return redirect(url_for('user_bp.update_password', email=email))
    return render_template("user/create_new_password.html")


@user_bp.route("/update_password", methods=['GET', 'POST'])
def update_password():
    if request.method == 'POST':
        user = db.session.query(User).filter(
            User.email == session.get("email")).first()
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        if password != confirm_password:
            flash('Password does not match !', 'danger')
        else:
            user.password = hashlib.sha256(password.encode()).hexdigest()
            session.clear()
            db.session.commit()
            return redirect(url_for('user_bp.user_login'))
    return render_template('user/update_password.html')


@login_required
@user_bp.route('/user/logout')
def user_logout():
    session.pop("email")
    return redirect(url_for('user_bp.home_page'))

fitness_management/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

fitness_management/templates/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="container mt-5">
  <div class="alert alert-{{ category }}"> {{ message}} </div>
</div>
{% endfor %}
{% endif %}
{% endwith %}

fitness_management/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

    <title>{{title}}</title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

fitness_management/templates/navbar.html
<!-- nav bar starta -->
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{url_for('user_bp.home_page')}}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if session['email'] %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('user_bp.user_logout')}}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('user_bp.user_profile')}}">{{session['email']}}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('user_bp.user_login')}}">Signin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('user_bp.user_register')}}">Signup</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>
<!-- navbar end -->