fitness_management/workout_planner/models.py
from ..database import db


class Workout(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    exercises = db.relationship('Exercise', backref='workout', lazy=True)


class Exercise(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    sets = db.Column(db.Integer, nullable=False)
    reps = db.Column(db.Integer, nullable=False)
    workout_id = db.Column(db.Integer, db.ForeignKey(
        'workout.id'), nullable=False)

fitness_management/workout_planner/routes.py
import ast
from flask import render_template, session, request, redirect, url_for, Blueprint, flash, make_response
from ..database import db
from .models import Workout, Exercise
import json
from werkzeug.security import generate_password_hash, check_password_hash
from fitness_management.user.routes import login_required, get_current_user
from flask import abort


workout_bp = Blueprint("workout_bp", __name__)


@workout_bp.route('/create_workout', methods=['GET', 'POST'])
@login_required
def create_workout():
    current_user = get_current_user()
    if request.method == 'POST':
        title = request.form.get('title')
        if title:
            workout = Workout(title=title, user_id=current_user.id)
            db.session.add(workout)
            db.session.commit()
            flash(f'New Workout Has Been Created', 'success')
            return redirect(url_for('workout_bp.list_workouts'))
    return render_template('workout_planner/create_workout.html', current_user=current_user)


@workout_bp.route('/workout/<int:id>', methods=['GET', 'POST'])
def workout_detail(id):
    current_user = get_current_user()
    workout = Workout.query.get_or_404(id)
    if workout.user_id != current_user.id:
        abort(403)  # Forbidden access
    if request.method == 'POST':
        name = request.form.get('name')
        sets = request.form.get('sets')
        reps = request.form.get('reps')
        if name and sets and reps:
            exercise = Exercise(name=name, sets=sets, reps=reps, workout_id=id)
            db.session.add(exercise)
            db.session.commit()
            flash(f'New Exercise Has Been Created', 'success')
            return redirect(url_for('workout_bp.workout_detail', id=id))
    return render_template('workout_planner/workout_detail.html', workout=workout, current_user=current_user)


@workout_bp.route("/updateexercise/<int:exercise_id>/<int:workout_id>", methods=['GET', 'POST'])
@login_required
def updateexercise(exercise_id, workout_id):
    workout = Workout.query.get_or_404(workout_id)
    exercise = Exercise.query.get_or_404(exercise_id)
    if request.method == 'POST':
        exercise.name = request.form.get("name")
        exercise.sets = request.form.get("sets")
        exercise.reps = request.form.get("reps")
        flash(f'Your Exercise has been updated', 'success')
        db.session.commit()
        return redirect(url_for('workout_bp.workout_detail', id=workout_id))
    return render_template('workout_planner/updateexercise.html', exercise=exercise, workout=workout)


@workout_bp.route("/delete_exercise/<int:exercise_id>/<int:workout_id>", methods=['GET', 'POST'])
@login_required
def delete_exercise(exercise_id, workout_id):
    exercise = Exercise.query.get_or_404(exercise_id)
    db.session.delete(exercise)
    flash(f'The Exercise {exercise.name} has been deleted', 'warning')
    db.session.commit()
    return redirect(url_for('workout_bp.workout_detail', id=workout_id))


@workout_bp.route("/updateworkout/<int:workout_id>", methods=['GET', 'POST'])
@login_required
def updateworkout(workout_id):
    workout = Workout.query.get_or_404(workout_id)
    if request.method == 'POST':
        workout.title = request.form.get("title")
        flash(f'Your Workout has been updated', 'success')
        db.session.commit()
        return redirect(url_for('workout_bp.list_workouts'))
    return render_template('workout_planner/updateworkout.html', workout=workout)


@workout_bp.route("/delete_workout/<int:workout_id>", methods=['GET', 'POST'])
@login_required
def delete_workout(workout_id):
    workout = Workout.query.get_or_404(workout_id)
    db.session.delete(workout)
    flash(f'The workout {workout.title} has been deleted', 'warning')
    db.session.commit()
    return redirect(url_for('workout_bp.list_workouts'))


@workout_bp.route('/list_workouts')
@login_required
def list_workouts():
    current_user = get_current_user()
    workouts = Workout.query.filter_by(user_id=current_user.id).all()
    return render_template('workout_planner/list_workouts.html', workouts=workouts)

fitness_management/templates/workout_planner/create_workout.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 mt-5">
                {% include '_messages.html' %}
                <div class="card">
                    <h2 class="text-center">Create New Workout</h2>
                    <form method="post">
                        <div class="form-group">
                            <label for="workout">Workout Title</label>
                            <input type="text" class="form-control" name="title" placeholder="Enter Workout Title">
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Create Workout </button>
                            </div>
                            <div class="col-md-6">
                                <a href="{{url_for('workout_bp.list_workouts')}}" class="btn btn-warning btn-custom btn-block mt-4">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock content %}

fitness_management/templates/workout_planner/list_workouts.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <h2 class="text-center">My Workouts</h2>
    {% include '_messages.html' %}
    {% if workouts %}
    <table class="modern-table">
        <thead>
          <tr>
            <th>Sr</th>
            <th>Workout Name</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for workout in workouts %}
          <tr>
            <td>{{loop.index}}</td>
            <td><a href="{{ url_for('workout_bp.workout_detail', id=workout.id) }}">{{ workout.title }}</a></td>
            <td><a href="{{ url_for('workout_bp.updateworkout', workout_id=workout.id) }}"
                class="btn btn-info btn-sm">Edit</a></td>
            <td>
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                data-target="#exampleModalLong-{{workout.id}}">
                Delete
              </button>
            </td>
          </tr>
            <!-- Modal -->
            <div class="modal fade" id="exampleModalLong-{{workout.id}}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">{{workout.title}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="text-danger ">Are you sure to delete {{workout.title}}</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal">Cancel</button>
                    <form action="{{url_for('workout_bp.delete_workout', workout_id = workout.id)}}" method="post">
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
                </div>
            </div>
            </div>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="text-center">
        <span class="emoji">&#x1F614;</span>
        <p class="text-danger h3">No Workout is Found</p>
      </div>
    {% endif %}
    <div class="text-center">
        <a href="{{ url_for('workout_bp.create_workout') }}" class="btn btn-info btn-custom mt-4">Create New Workout</a>
    </div>    
</div>

{% endblock %}

fitness_management/templates/workout_planner/updateexercise.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <div>
        <h3>{{ workout.title }}</h2>
    </div>
    <div class="row mt-5">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <h2 class="text-center">Update Exercise</h2>
                <form method="post">
                    <div class="form-group">
                        <label for="workout">Exercise Name</label>
                        <input type="text" value="{{exercise.name}}" class="form-control" name="name" placeholder="Enter Exercise Name">
                    </div>
                    <div class="form-group">
                        <label for="workout">Sets</label>
                        <input type="number" value="{{exercise.sets}}" class="form-control" name="sets" placeholder="Enter Number OF Sets">
                    </div>
                    <div class="form-group">
                        <label for="workout">Reps</label>
                        <input type="number" value="{{exercise.reps}}" class="form-control" name="reps" placeholder="Enter Number OF Reps">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Add Exercise </button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{url_for('workout_bp.workout_detail',id =workout.id )}}" class="btn btn-warning btn-custom btn-block mt-4">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
            
    </div>
</div>
{% endblock %}

fitness_management/templates/workout_planner/updateworkout.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 mt-5">
                {% include '_messages.html' %}
                <div class="card">
                    <h2 class="text-center">Update Workout</h2>
                    <form method="post">
                        <div class="form-group">
                            <label for="workout">Workout Title</label>
                            <input type="text" value="{{workout.title}}" class="form-control" name="title" placeholder="Enter Workout Title">
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Update Workout </button>
                            </div>
                            <div class="col-md-6">
                                <a href="{{url_for('workout_bp.list_workouts')}}" class="btn btn-warning btn-custom btn-block mt-4">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock content %}

fitness_management/templates/workout_planner/workout_detail.html
{% extends "layout.html" %}
{% include 'navbar.html' %}
{% block content %}
<div class="container">
    <h2 class="text-center">{{ workout.title }}</h2>
    {% include '_messages.html' %}
<div class="row mt-5">
    <div class="col-md-8">

        {% if workout.exercises %}
        <table class="modern-table">
            <thead>
              <tr>
                <th>Sr</th>
                <th>Exercise Name</th>
                <th>Sets</th>
                <th>Reps</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for exercise in workout.exercises %}
              <tr>
                <td>{{loop.index}}</td>
                <td>{{ exercise.name }}</td>
                <td>{{ exercise.sets }}</td>
                <td>{{ exercise.reps }}</td>
                <td><a href="{{ url_for('workout_bp.updateexercise', exercise_id=exercise.id, workout_id=workout.id) }}"
                  class="btn btn-info btn-sm">Edit</a></td>
                <td>
                  <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                  data-target="#exampleModalLong-{{exercise.id}}">
                  Delete
                </button>
                </td>
              </tr>
                          <!-- Modal -->
            <div class="modal fade" id="exampleModalLong-{{exercise.id}}" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">{{exercise.name}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="text-danger ">Are you sure to delete {{exercise.name}}</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal">Cancel</button>
                    <form action="{{url_for('workout_bp.delete_exercise',exercise_id = exercise.id, workout_id = workout.id)}}" method="post">
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
                </div>
            </div>
            </div>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <div class="text-center">
            <span class="emoji">&#x1F614;</span>
            <p class="text-danger h3">No Exercise is Found</p>
          </div>
        {% endif %}
    </div>
    <div class="col-md-4">
        <h3>Add New Exercise</h3>
            <div class="card">
                <h2 class="text-center">Create New Exercise</h2>
                <form method="post">
                    <div class="form-group">
                        <label for="workout">Exercise Name</label>
                        <input type="text" class="form-control" name="name" placeholder="Enter Exercise Name">
                    </div>
                    <div class="form-group">
                        <label for="workout">Sets</label>
                        <input type="number" class="form-control" name="sets" placeholder="Enter Number OF Sets">
                    </div>
                    <div class="form-group">
                        <label for="workout">Reps</label>
                        <input type="number" class="form-control" name="reps" placeholder="Enter Number OF Reps">
                    </div>
                    <button type="submit" class="btn btn-info btn-custom btn-block mt-4">Add Exercise </button>
                </form>
                <div class="mt-3">
                    {% if current_user.role == "Admin" %}
                        <a href="{{ url_for('user_bp.admin_dashboard') }}">Back to Dashboard</a>
                        {% elif current_user.role == "Trainer" %}
                        <a href="{{ url_for('user_bp.trainer_dashboard') }}">Back to Dashboard</a>
                        {% else %}
                        <a href="{{ url_for('user_bp.member_dashboard') }}">Back to Dashboard</a>
                    {% endif %}
                </div>
            </div>
    </div>
</div>
</div>
{% endblock %}